---
groups:
- name: all
  jobs:
  - benchmark_zedstore


resources:
- name: postgres_src
  type: git
  source:
    uri: {{postgres_repo_uri}}
    branch: {{postgres_repo_branch}}

- name: tpch_dbgen_src
  type: git
  source:
    uri: https://github.com/tvesely/vops
    branch: update_interfaces_to_13_dev

- name: gpdb6_build_image
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-centos7-build
    tag: 'latest'

jobs:
- name: benchmark_zedstore
  plan:
  - aggregate:
    - get: postgres_src
      trigger: true
    - get: tpch_dbgen_src
    - get: gpdb6_build_image
  - aggregate:
    - task: run_benchmark
      file: postgres_src/concourse/tasks/run_benchmark.yaml
      params:
        EXTRA_CONFIGURE_FLAGS: ""
        SCALE_FACTOR: 10
      image: gpdb6_build_image
    - task: run_benchmark_lz4
      file: postgres_src/concourse/tasks/run_benchmark.yaml
      params:
        EXTRA_CONFIGURE_FLAGS: "--with-lz4"
        SCALE_FACTOR: 10
      image: gpdb6_build_image
