---
platform: linux
image_resource:
  type: docker-image
inputs:
  - name: postgres_src
  - name: tpch_dbgen_src

run:
  path: sh
  args: 
  - -exc
  - |
    # Install lz4
    yum install -y liblz4

    # Set up postgres user
    getent passwd postgres|| useradd postgres

    su -u postgres -c "postgres_src/concourse/scripts/install_postgres.sh"
    su -u postgres -c "postgres_src/concourse/scripts/zedstore_perf_test.sh"
params:
  EXTRA_CONFIGURE_FLAGS: ""
  SCALE_FACTOR: 1
