---
platform: linux
image_resource:
  type: docker-image
inputs:
  - name: postgres_src
  - name: tpch_dbgen_src
  - name: vops_src

run:
  path: sh
  args: 
  - -exc
  - |
    # Install lz4
    yum install -y lz4-devel

    # Set up postgres user
    getent passwd postgres|| useradd postgres

    postgres_src/concourse/scripts/install_postgres.sh
    su -c "postgres_src/concourse/scripts/initdb.sh" postgres
    su -c "postgres_src/concourse/scripts/zedstore_perf_test.sh" postgres
params:
  EXTRA_CONFIGURE_FLAGS: ""
  SCALE_FACTOR: 1
